controller_manager:
  ros__parameters:
    update_rate: 2  # Hz

    joint_state_controller:
      type: joint_state_controller/JointStateController

    effort_controllers:
      type: effort_controllers/JointGroupEffortController

effort_controllers:
  ros__parameters:
    joints:
      - a1_joint