controller_manager:
  ros__parameters:
    update_rate: 1  # Hz

    joint_state_controller:
      type: joint_state_broadcaster/JointStateBroadcaster

    effort_controllers:
      type: effort_controllers/JointGroupEffortController

effort_controllers:
  ros__parameters:
    joints:
      - a1_joint
    command_interfaces:
      - effort
    state_interfaces:
      - position
      - velocity
      - effort